name: meald
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  http: ^1.2.2 
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  geolocator: ^13.0.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0 
  flutter_bloc: ^8.1.0  
  image_picker: ^0.8.6
  fl_chart: ^0.69.0  


dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mealdLogo.gif
    - assets/Driver.gif
    - assets/Location.gif
    - assets/logo.gif
    - assets/LOGO.png
    - assets/mealdLogo.jpg
    - assets/User.gif
    - assets/addpic.png
    - assets/profileBG.jpg
    - assets/home.png
    - assets/list.png
    - assets/add.png
    - assets/notif.png
    - assets/profile.png
    - assets/test.png
    - assets/userlogo.png
